#!/bin/bash

# Print a blank line at the beginning for clean output
echo ""

# Get the hostname of the system
HOSTNAME=$(hostname)

# Get the current username
USERNAME=$(whoami)

# Get the current date and time
DATETIME=$(date)

# Load OS information from system file
source /etc/os-release
OS="$NAME $VERSION"

# Get system uptime in human-readable format
UPTIME=$(uptime -p)

# Get CPU model name using lshw (filter and clean output)
CPU=$(lshw -C processor 2>/dev/null | grep "product" | awk -F: '{print $2}' | xargs)

# Get total installed RAM
RAM=$(free -h | grep Mem | awk '{print $2}')

# Get info about all installed disks
DISK=$(lshw -class disk 2>/dev/null | grep product | awk -F: '{print $2}' | xargs)

# Get video card make and model
VIDEO=$(lshw -C display 2>/dev/null | grep product | awk -F: '{print $2}' | xargs)

# Get the IP address used to connect to the default gateway
HOST_IP=$(hostname -I | awk '{print $1}') 


# Get the default gateway IP address
GATEWAY=$(ip route | grep default | awk '{print $3}')

# Get the first DNS server IP address
DNS=$(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -n 1)

# Get a comma-separated list of logged-in users (no duplicates)
USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)

# Get available disk space for each mount point
DISK_SPACE=$(df -h --output=target,avail | tail -n +2 | awk '{print $1 " " $2}' | xargs)

# Get the total number of running processes
PROC_COUNT=$(ps -e | wc -l)

# Get system load averages (1, 5, and 15 minutes)
LOAD_AVG=$(uptime | awk -F'load average:' '{print $2}' | xargs)

# Get a list of all listening network ports (TCP/UDP)
PORTS=$(ss -tuln 2>/dev/null | awk 'NR>1 {print $5}' | awk -F: '{print $NF}' | grep -E '^[0-9]+$' | sort -n | uniq | paste -sd "," -)

# Get the status of UFW (Uncomplicated Firewall)
UFW_STATUS=$(sudo ufw status | head -n 1)

# Print the final report exactly in the required format
cat <<EOF
System Report for $HOSTNAME generated by $USERNAME, on $DATETIME

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISK
Video: $VIDEO
Host Address: $HOST_IP
Gateway IP: $GATEWAY
DNS Server: $DNS

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROC_COUNT
Load Averages: $LOAD_AVG
Listening Network Ports: $PORTS
UFW Status: $UFW_STATUS
EOF

# Print a blank line at the end for clean shell prompt
echo ""
